version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/" # Workflow files stored in the default location of `.github/workflows`
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/" # Workflow files stored in the default location of `.github/workflows`
    schedule:
      interval: "weekly"

