version: '2'
run:
  timeout: 5m
linters:
  enable:
    - decorder
    - errorlint
    - gocyclo
    - govet
    - gosec
    - gosmopolitan
    - intrange
    - misspell
    - predeclared
    - reassign
    - staticcheck
    - unconvert
    - unparam
    - usestdlibvars
    - wastedassign
    - copyloopvar
    - tparallel
  settings:
    gocyclo:
      min-complexity: 30
    gosec:
      excludes:
        - G404 # deterministic RNG in tests/benchmarks only
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$

formatters:
  enable:
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
