name: CI
on:
  push:
    branches: ["main", "devel"]
    paths:
      - '**.go'
      - '**.yml'
      - '**.yaml'
  pull_request:
    branches: ["main"]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      fail-fast: true
      matrix:
        go-version: ['stable', 'oldstable']
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}
          cache: true
      - run: go test -v ./...
      - if: runner.os == 'Linux'
        run: go test -v -race -run='(Persist|Example)'

  govulncheck:
    strategy:
      fail-fast: false
      matrix:
        go-version: ['stable', 'oldstable']
        os: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - id: go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}
          cache: true
      - uses: golang/govulncheck-action@v1
        with:
          go-version-input: ${{ steps.go.outputs.go-version }}
          check-latest: true

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: stable
          cache: true

      - name: Test Coverage
        run: go test -v -coverprofile=profile.cov ./...

      - uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: profile.cov

  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: stable
          cache: true

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
