name: CI
on:
  push:
    branches: ["main", "devel"]
    paths: &paths
      - 'go.mod'
      - 'go.sum'
      - '**.go'
      - '**.yaml'
      - '**.yml'
  pull_request:
    branches: ["main", "devel"]
    paths: *paths

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test (Ubuntu / Go ${{ matrix.go-version-name }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go-version-name: ['stable', 'from-gomod']
        include:
          - go-version-name: 'stable'
            go-version: 'stable'
          - go-version-name: 'from-gomod'
            go-version-file: 'go.mod'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}
          go-version-file: ${{ matrix.go-version-file }}
          cache: true

      - name: Install Dependencies
        run: go mod download

      - name: Run Tests
        run: go test -v ./...

      - name: Run -race Tests
        run: go test -v -race -run='(Persist|Example)' ./...

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false

      - uses: actions/setup-go@v6
        with:
          go-version: stable
          cache: true

      - name: Test Coverage
        run: go test -v -coverprofile=profile.cov ./...

      - uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: profile.cov

  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false

      - uses: actions/setup-go@v6
        with:
          go-version: stable
          cache: false

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: latest
