name: CI
on:
  push:
    branches: ["main"]
    paths:
    - '**.go'
    - '**.yml'
  pull_request:
    branches: ["main"]  

jobs:
  test:
    strategy:
      matrix:
        go-version: ['1.21']
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v3
      - run: go test -v ./...      
  
  govulncheck:
    runs-on: ubuntu-latest
    steps:
      - uses: golang/govulncheck-action@v1
        with:
          go-version-input: 1.21
          check-latest: true
      
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3         
      - uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Test Coverage
        run: go test -v -coverprofile=profile.cov ./...

      - uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: profile.cov

  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 1.21
          
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
