name: CI
on:
  push:
    branches: ["main", "devel"]
    paths: &paths
      - 'go.mod'
      - 'go.sum'
      - '**.go'
      - '**.yaml'
      - '**.yml'
  pull_request:
    branches: ["main", "devel"]
    paths: *paths

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      fail-fast: true
      matrix:
        go-version-file: go.mod
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false

      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: true

      - run: go test -v ./...

      - if: matrix.os == 'ubuntu-latest'
        run: go test -v -race -run='(Persist|Example)' ./...

  govulncheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false

      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: true

      - uses: golang/govulncheck-action@v1
        id: govulncheck

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false

      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: true

      - name: Test Coverage
        run: go test -v -coverprofile=profile.cov ./...

      - uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: profile.cov

  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false

      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: false

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: latest
